language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

install:
  - cd ./simulation-engine
  - mvn install -DskipTests=true
  - mvn test
  
before_script:
  - cd ../eu.scape_project.pw.simulator.releng
  - mvn install -DskipTests=true

script:
  - mvn test
