language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
before_script:
  - cd ./simulation-engine
  - mvn install -DskipTests=true
  - cd ..
  - cd ./eclipse-plugin
  - mvn install -DskipTests=true

script:
  - cd ./simulation-engine
  - mvn test
  - cd ./eclipse-plugin
  - mvn test
